name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [ opened, synchronize ]

jobs:
  build:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest
    # To use Remote Caching, uncomment the next lines and follow the steps below.
    # env:
    #  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
    #  TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    # Set up a local Postgres database for db-shopshop.
    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: shopshop
          POSTGRES_PORT: 5432
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out code
        uses: actions/checkout@v6
        with:
          fetch-depth: 2

      - name: Set up pnpm
        uses: pnpm/action-setup@v6

      - name: Setup Node.js environment
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Ensure tsconfig exports are available for TypeScript
        run: node ./scripts/prepare-tsconfig-exports.js

      - name: Generate Prisma client and migrate to dummy database for db-shopshop
        working-directory: packages/db-shopshop
        run: |
          echo "DATABASE_URL=postgres://postgres:postgres@localhost:5432/shopshop" > .env
          pnpm run db-shopshop:generate
          pnpm run db-shopshop:migrate

      - name: Build
        env:
          CI: true
        run: pnpm build

      - name: Test
        run: pnpm test:ci
